name: "Infraestrutura básica para as aplicações"

on:
  push:
    branches: 
      - '**'    # Aceita push em qualquer branch
  pull_request:

jobs:
  validacao_autenticacao_aws:
    name: "Validação de autenticação na AWS"
    run-on: ubuntu-latest
    steps:
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Valida credenciais AWS
        run: aws sts get-caller-identity