name: "Criação de Infraestrutura básica para as aplicações"
on:
  push:
    branches: 
      - '**'    # Aceita push em qualquer branch
  pull_request:

jobs:
  cria_infra:
    name: "Criação de infra para aplicações do techchallenge"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4.2.2
      
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Realiza setup do Terraform
        run: ./setup.sh

      - name: Setup do Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.3"

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=env/dev fmt -check

      - name: Terraform Init
        id: init
        run: terraform -chdir=env/dev init
      
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=env/dev validate -no-color
      
