name: "Criação de Infraestrutura básica para as aplicações"
on:
  push:
    branches: [main, develop]
  pull_request:

permissions:
  issues: write
  pull-requests: write
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ (github.ref_name == 'main' || github.event_name == 'pull_request') && 'prod' || 'dev' }}  
      enable_plan: ${{ github.event_name == 'pull_request' || github.ref_name == 'develop' }}
      enable_apply: ${{ (github.ref_name == 'main' || github.ref_name == 'develop') && github.event_name == 'push' }}
      enable_write_comments: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4.2.2
  
  terraform_common:      
    needs: init
    uses: ./.github/workflows/terraform.yaml
    secrets: inherit
    with:
      environment: ${{ needs.init.outputs.environment }}
      terraform_dir: "terraform/common"
      enable_plan: ${{ needs.init.outputs.enable_plan }}
      enable_apply: ${{ needs.init.outputs.enable_apply }}
      enable_write_comments: ${{ needs.init.outputs.enable_write_comments }}
  
  terraform_env:
    needs: init
    uses: ./.github/workflows/terraform.yaml
    secrets: inherit
    with:
      environment: ${{ needs.init.outputs.environment }}
      terraform_dir: "terraform/env/${{ needs.init.outputs.environment }}"
      enable_plan: ${{ needs.init.outputs.enable_plan }}
      enable_apply: ${{ needs.init.outputs.enable_apply }}
      enable_write_comments: ${{ needs.init.outputs.enable_write_comments }}