name: "Infraestrutura básica para as aplicações"

on:
  push:
    branches: 
      - '**'    # Aceita push em qualquer branch
  pull_request:

jobs:
  validacao_autenticacao_aws:
    name: "Validação de autenticação na AWS"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4.2.2
      
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Realiza setup do Terraform
        run: ./setup.sh
      
