on:
  workflow_call:
    inputs:      
      environment:
        required: true
        type: string
      terraform_dir:
        required: true
        type: string
      enable_plan:
        required: true
        type: string
      enable_apply:
        required: true
        type: string
      is_pull_request:
        required: true
        type: boolean
permissions:
  issues: write
  pull-requests: write
jobs:  
  terraform:    
    runs-on: ubuntu-latest
    env:
      TF_VAR_environment: ${{ inputs.enable_apply }}
    steps:      
      - uses: actions/checkout@v4.2.2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Run Terraform backend setup
        run: ./setup.sh

      - name: Setup do Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.3"

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=${{inputs.terraform_dir}} fmt -check

      - name: Terraform Init
        id: init
        run: terraform -chdir=${{inputs.terraform_dir}} init
      
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=${{inputs.terraform_dir}} validate -no-color

      - name: Terraform Plan
        id: plan
        if: ${{ inputs.enable_plan == 'true'}} 
        run: terraform -chdir=${{inputs.terraform_dir}} plan -no-color -input=false
        continue-on-error: true

      - name: Atualização do Pull Request
        uses: actions/github-script@v7
        if: ${{ inputs.is_pull_request == 'true' }}
        env:
          PLAN: ${{ steps.plan.outputs.stdout }}
        with:
          script: |
            const output = `#### Terraform - Formatação e Estilo 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Init ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validação 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Detalhes do Terraform Plan</summary>

            \`\`\`terraform\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Enviado por: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: ${{ inputs.enable_apply == 'true' }}
        run: terraform -chdir=${{inputs.terraform_dir}} apply -auto-approve -input=false
      
